export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_PASSWORD_VISIBLE = 'LOGIN_PASSWORD_VISIBLE';
export const SIGNUP_PASSWORD_VISIBLE = 'SIGNUP_PASSWORD_VISIBLE';
export const SIGNUP_VISIBLE = 'SIGNUP_VISIBLE';
export const GET_USERS = 'GET_USERS';